project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - research.qmd
    - teaching.qmd
    - resources.qmd
    - icpsr-2026/index.qmd
  resources:
    - google6306c6a89f6a4388.html
    - icpsr-2026/*.html
    - icpsr-2026/*_files/**

website:
  title: "Will Horne"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - resources.qmd
  page-footer:
    center: "© {year} Will Horne"
  site-url: "https://will-horne.github.io/"

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
    link-external-newwindow: true
