<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Will Horne">
  <title>POSC 8410 — Fall 2026 – POSC 8410: Conditional Probability and Bayes’ Rule</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">POSC 8410: Conditional Probability and Bayes’ Rule</h1>
  <p class="subtitle">Conditioning is the whole game</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Will Horne 
</div>
</div>
</div>

</section>
<section id="where-we-are" class="slide level2">
<h2>Where We Are</h2>
<ul>
<li class="fragment"><p>Last time: sample spaces, axioms, and counting</p></li>
<li class="fragment"><p>Today: Conditional Probability</p></li>
</ul>
<div class="fragment">
<p>Nearly every question you will ask as a social scientist is a <strong>conditional</strong> one. Today we learn how to reason about <strong>conditional</strong> probability.</p>
</div>
</section>
<section>
<section id="conditional-probability" class="title-slide slide level1 center">
<h1>Conditional Probability</h1>

</section>
<section id="conditioning-is-the-whole-thing" class="slide level2">
<h2>Conditioning Is the Whole Thing</h2>
<ul>
<li class="fragment"><p>Does a child attend college <em>given</em> a policy intervention?</p></li>
<li class="fragment"><p>Does hospitalization risk differ <em>between</em> vaccinated and unvaccinated people?</p></li>
<li class="fragment"><p>Do people vote more <em>when told</em> their turnout is visible to neighbors?</p></li>
<li class="fragment"><p>Does a résumé get a callback <em>given</em> the name at the top?</p></li>
</ul>
<div class="fragment">
<p><strong>Unconditional:</strong> what is the probability of <span class="math inline">\(A\)</span>?</p>
<p><strong>Conditional:</strong> given that <span class="math inline">\(B\)</span> happened, what is the probability of <span class="math inline">\(A\)</span>?</p>
</div>
</section>
<section id="the-definition" class="slide level2">
<h2>The Definition</h2>
<p>If <span class="math inline">\(P(B) &gt; 0\)</span>:</p>
<p><span class="math display">\[P(A \mid B) = \frac{P(A \cap B)}{P(B)}\]</span></p>
<div class="fragment">
<p>How often <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> happen together, divided by how often <span class="math inline">\(B\)</span> happens at all.</p>
</div>
<div class="fragment">
<ul>
<li class="fragment"><p>Conditioning <strong>shrinks the sample space</strong>. We are no longer asking about everyone -only about the <span class="math inline">\(B\)</span> world.</p></li>
<li class="fragment"><p>Dividing by <span class="math inline">\(P(B)\)</span> re-normalizes so the new, smaller world still sums to 1</p></li>
</ul>
</div>
</section>
<section id="the-senate" class="slide level2">
<h2>The Senate</h2>
<p>A snapshot of a 100-seat chamber:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Democrats</th>
<th style="text-align: right;">Republicans</th>
<th style="text-align: right;">Independents</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Men</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td>Women</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>48</strong></td>
<td style="text-align: right;"><strong>49</strong></td>
<td style="text-align: right;"><strong>3</strong></td>
<td style="text-align: right;">100</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Pick one senator at random. What is <span class="math inline">\(P(\text{woman} \mid \text{Democrat})\)</span>?</p>
</div>
</section>
<section id="working-it-out" class="slide level2">
<h2>Working It Out</h2>
<ul>
<li class="fragment"><p><span class="math inline">\(P(\text{woman} \mid \text{Democrat}) = \dfrac{15/100}{48/100} = \dfrac{15}{48} = 0.31\)</span></p></li>
<li class="fragment"><p>We threw away 52 senators. The denominator is no longer 100 - it’s 48.</p></li>
</ul>
<div class="fragment">
<p>Now the other direction: <span class="math inline">\(P(\text{Republican} \mid \text{woman})\)</span>?</p>
</div>
<div class="fragment">
<p><span class="math display">\[\frac{9/100}{25/100} = \frac{9}{25} = 0.36\]</span></p>
</div>
</section>
<section id="pa-mid-b-is-not-pb-mid-a" class="slide level2">
<h2><span class="math inline">\(P(A \mid B)\)</span> Is Not <span class="math inline">\(P(B \mid A)\)</span></h2>
<ul>
<li class="fragment"><p><span class="math inline">\(P(\text{woman} \mid \text{Democrat}) = 0.31\)</span></p></li>
<li class="fragment"><p><span class="math inline">\(P(\text{Democrat} \mid \text{woman}) = 15/25 = 0.60\)</span></p></li>
<li class="fragment"><p>We met this in Week 2: <em>“among Biden voters, 88% favor taxing the rich”</em> is not <em>“among supporters of taxing the rich, 88% voted for Biden”</em></p></li>
</ul>
<div class="fragment">
<p>Confusing the two is one of the most common errors in applied social science — and, as we will see today, in courtrooms and policy debates.</p>
</div>
</section>
<section id="conditional-probabilities-are-probabilities" class="slide level2">
<h2>Conditional Probabilities Are Probabilities</h2>
<ul>
<li class="fragment"><p><span class="math inline">\(P(A \mid B)\)</span> satisfies each axiom from last week</p></li>
<li class="fragment"><p><span class="math inline">\(P(A \mid A) = 1\)</span></p></li>
<li class="fragment"><p><span class="math inline">\(P(A^{c} \mid B) = 1 - P(A \mid B)\)</span></p></li>
</ul>
<div class="fragment">
<p>But be careful — the conditioning bar is not additive. Why is this false?</p>
<p><span class="math display">\[P(A \mid B \cup C) \neq P(A \mid B) + P(A \mid C)\]</span></p>
</div>
</section></section>
<section>
<section id="joint-probability-and-total-probability" class="title-slide slide level1 center">
<h1>Joint Probability and Total Probability</h1>

</section>
<section id="joint-probabilities" class="slide level2">
<h2>Joint Probabilities</h2>
<p>The probability that both happen, written <span class="math inline">\(P(A \cap B)\)</span> or <span class="math inline">\(P(A, B)\)</span>.</p>
<div class="fragment">
<p>Rearranging the definition of conditional probability:</p>
<p><span class="math display">\[P(A, B) = P(A)\,P(B \mid A) = P(B)\,P(A \mid B)\]</span></p>
</div>
<div class="fragment">
<ul>
<li class="fragment"><p>Two ways to describe the same result</p></li>
<li class="fragment"><p>That symmetry is the basis of Bayes’ rule (coming later today)</p></li>
</ul>
</div>
</section>
<section id="the-law-of-total-probability" class="slide level2 smaller">
<h2>The Law of Total Probability</h2>
<ul>
<li class="fragment"><p>Suppose we know candidate support in <strong>each city</strong> of a state. How do we get statewide support?</p></li>
<li class="fragment"><p>The cities form a <strong>partition</strong>: mutually disjoint events whose union is the whole sample space</p></li>
<li class="fragment"><p>If <span class="math inline">\(A_1, \ldots, A_k\)</span> is a partition:</p>
<p><span class="math display">\[P(B) = \sum_{j=1}^{k} P(B \mid A_j)\, P(A_j)\]</span></p></li>
</ul>
<div class="fragment">
<p>In words: take the conditional probability in each piece, <strong>weight it by how big that piece is</strong>, and add up.</p>
</div>
</section>
<section id="a-simplified-georgia" class="slide level2">
<h2>A Simplified Georgia</h2>
<p>Three cities, with support for one candidate:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>City</th>
<th style="text-align: right;"><span class="math inline">\(P(\text{support} \mid \text{city})\)</span></th>
<th style="text-align: right;">Voters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Atlanta</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">500,000</td>
</tr>
<tr class="even">
<td>Peachtree City</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">80,000</td>
</tr>
<tr class="odd">
<td>Helen</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">20,000</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Two of the three cities look bad. Is the candidate losing?</p>
</div>
</section>
<section id="weight-by-size" class="slide level2">
<h2>Weight by Size</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a>support <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.60</span>, <span class="fl">0.15</span>, <span class="fl">0.10</span>)</span>
<span id="cb1-2"><a></a>voters  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">500000</span>, <span class="dv">80000</span>, <span class="dv">20000</span>)</span>
<span id="cb1-3"><a></a></span>
<span id="cb1-4"><a></a>weights <span class="ot">&lt;-</span> voters <span class="sc">/</span> <span class="fu">sum</span>(voters)</span>
<span id="cb1-5"><a></a>weights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.83333333 0.13333333 0.03333333</code></pre>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="fu">sum</span>(support <span class="sc">*</span> weights)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5233333</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p><strong>52.3%.</strong> Two of three cities went against them and they still lead, because Atlanta is 83% of the electorate.</p>
</div>
</section>
<section id="why-this-matters" class="slide level2">
<h2>Why This Matters</h2>
<ul>
<li class="fragment"><p>Averaging the three city rates gives <span class="math inline">\((0.60 + 0.15 + 0.10)/3 = 0.28\)</span> — wrong by 24 points</p></li>
<li class="fragment"><p>The conditional probabilities were all correct. But, the <strong>weights</strong> matter.</p></li>
</ul>
<div class="fragment">
<p>This is exactly the error behind “I drove through the county and saw nothing but signs for the other guy.” Unweighted conditionals are not a population estimate.</p>
</div>
</section>
<section id="you-may-have-seen-this-map" class="slide level2">
<h2>You May Have Seen This Map</h2>

<img data-src="06_Conditional_Probability_Bayes_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"><div style="font-size: 0.62em; color: grey;">
<p>Contiguous 48 shown. County returns: tonmcg/US_County_Level_Election_Results.</p>
</div>
<div class="fragment">
<p>Trump carried <strong>2,595</strong> counties; Biden carried <strong>557</strong> — and won the popular vote by 4.5 points. It is a map of <strong>land</strong>, read as a map of <strong>people</strong>.</p>
</div>
</section>
<section id="why-the-map-misleads" class="slide level2 smaller">
<h2>Why the Map Misleads</h2>
<ul>
<li class="fragment"><p>A choropleth gives every county the same visual weight <strong>per square mile</strong></p></li>
<li class="fragment"><p>Los Angeles County has roughly 10 million residents. Several counties have fewer than a thousand. On the map, each is one patch.</p></li>
<li class="fragment"><p>The map shows <span class="math inline">\(P(\text{support} \mid \text{county})\)</span> and hides <span class="math inline">\(P(\text{county})\)</span> — the missing weight from the law of total probability. <strong>The map is the unweighted average.</strong></p></li>
</ul>
<div class="fragment">
<p>The general lesson: group rates are not a population estimate until you weight them. Whenever anyone shows you rates by county, school, state, or country, ask: <strong>how big is each group?</strong></p>
</div>
</section></section>
<section>
<section id="bayes-rule" class="title-slide slide level1 center">
<h1>Bayes’ Rule</h1>

</section>
<section id="a-public-health-decision" class="slide level2">
<h2>A Public Health Decision</h2>
<p>You are a regulator. A firm brings you a screening test for a deadly cancer.</p>
<ul>
<li class="fragment"><p>It detects the cancer <strong>99%</strong> of the time when present</p></li>
<li class="fragment"><p>It has only a <strong>3%</strong> false positive rate</p></li>
<li class="fragment"><p>They want you to approve it for routine population-wide screening</p></li>
</ul>
<div class="fragment">
<p>Those are genuinely good test characteristics. Do you approve it?</p>
</div>
</section>
<section id="what-is-missing" class="slide level2">
<h2>What Is Missing?</h2>
<ul>
<li class="fragment"><p>The question you have to answer is not “how good is the test?”</p></li>
<li class="fragment"><p>It is: <strong>if a random person screens positive, how likely are they to have the cancer?</strong></p></li>
<li class="fragment"><p>To answer that you need one more number the sales rep did not give you - the <strong>base rate</strong></p></li>
</ul>
<div class="fragment">
<p>Suppose prevalence is 1 in 1,000. That would make it a very common cancer.</p>
</div>
</section>
<section id="bayes-rule-1" class="slide level2">
<h2>Bayes’ Rule</h2>
<p>Reverend Thomas Bayes (1701–1761), English minister and statistician.</p>
<div class="fragment">
<p>If <span class="math inline">\(P(B) &gt; 0\)</span>:</p>
<p><span class="math display">\[P(A \mid B) = \frac{P(B \mid A)\, P(A)}{P(B)}\]</span></p>
</div>
<div class="fragment">
<p>It falls out of the joint probability identity: both <span class="math inline">\(P(A)P(B|A)\)</span> and <span class="math inline">\(P(B)P(A|B)\)</span> equal <span class="math inline">\(P(A,B)\)</span>, so set them equal and divide.</p>
</div>
</section>
<section id="expanding-the-denominator" class="slide level2">
<h2>Expanding the Denominator</h2>
<p>Usually we do not know <span class="math inline">\(P(B)\)</span> directly, so we build it with the law of total probability:</p>
<p><span class="math display">\[P(A \mid B) = \frac{P(B \mid A)\, P(A)}{P(B \mid A)P(A) + P(B \mid A^{c})P(A^{c})}\]</span></p>
<ul>
<li class="fragment"><p><span class="math inline">\(P(A)\)</span> is the <strong>prior</strong> - what we believed before the evidence</p></li>
<li class="fragment"><p><span class="math inline">\(P(A \mid B)\)</span> is the <strong>posterior</strong> - what we believe after</p></li>
<li class="fragment"><p>The denominator is just “all the ways <span class="math inline">\(B\)</span> could happen”</p></li>
</ul>
</section>
<section id="run-the-numbers" class="slide level2">
<h2>Run the Numbers</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a>prior <span class="ot">&lt;-</span> <span class="fl">0.001</span>    <span class="co"># P(cancer)</span></span>
<span id="cb5-2"><a></a>sens  <span class="ot">&lt;-</span> <span class="fl">0.99</span>     <span class="co"># P(positive | cancer)</span></span>
<span id="cb5-3"><a></a>fpr   <span class="ot">&lt;-</span> <span class="fl">0.03</span>     <span class="co"># P(positive | no cancer)</span></span>
<span id="cb5-4"><a></a></span>
<span id="cb5-5"><a></a>(sens <span class="sc">*</span> prior) <span class="sc">/</span> (sens <span class="sc">*</span> prior <span class="sc">+</span> fpr <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> prior))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03197674</code></pre>
</div>
</div>
<div class="fragment">
<p><strong>3.2%.</strong> A positive result on this excellent test means you probably do not have the disease.</p>
</div>
</section>
<section id="seeing-it" class="slide level2">
<h2>Seeing It</h2>

<img data-src="06_Conditional_Probability_Bayes_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"><p>Screen 100,000 people. Only 100 have the cancer, and the test finds 99 of them - but it also flags 3% of the 99,900 healthy people.</p>
</section>
<section id="why-the-base-rate-dominates" class="slide level2">
<h2>Why the Base Rate Dominates</h2>
<ul>
<li class="fragment"><p>The test is applied to a <strong>huge</strong> healthy group and a <strong>tiny</strong> sick group</p></li>
<li class="fragment"><p>3% of an enormous number beats 99% of a very small one</p></li>
<li class="fragment"><p>This is the <strong>base rate fallacy</strong>: judging <span class="math inline">\(P(\text{disease} \mid +)\)</span> by <span class="math inline">\(P(+ \mid \text{disease})\)</span> and forgetting how rare the disease is</p></li>
</ul>
<div class="fragment">
<p>Note what this does <em>not</em> say. The test is not useless - it moved you from 0.1% to 3.2%, a <strong>thirtyfold</strong> update. It just is not a diagnosis.</p>
</div>
</section>
<section id="this-is-a-live-policy-question" class="slide level2">
<h2>This Is a Live Policy Question</h2>
<p>Several states have required drug testing for public benefit applicants. Suppose 10% of applicants use drugs, and the test is 95% sensitive with a 5% false positive rate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a>p <span class="ot">&lt;-</span> <span class="fl">0.1</span>; s <span class="ot">&lt;-</span> <span class="fl">0.95</span>; f <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb7-2"><a></a>(s <span class="sc">*</span> p) <span class="sc">/</span> (s <span class="sc">*</span> p <span class="sc">+</span> f <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6785714</code></pre>
</div>
</div>
<div class="fragment">
<ul>
<li class="fragment"><p>About <strong>68%</strong>. Roughly three in ten people flagged would be false accusations.</p></li>
<li class="fragment"><p>Reported positive rates in real programs have been lower than this - which makes the arithmetic tough.</p></li>
</ul>
</div>
<div class="fragment">
<p>You cannot evaluate a screening policy without a base rate.</p>
</div>
</section>
<section id="the-prosecutors-fallacy" class="slide level2 smaller">
<h2>The Prosecutor’s Fallacy</h2>
<p>A murder is committed. Crime scene evidence shows the murderer has a blood type shared by 5% of the population. A suspect matches.</p>
<div class="fragment">
<p>The prosecutor tells the jury this establishes a <strong>95% chance</strong> the suspect is the murderer.</p>
</div>
<div class="fragment">
<ul>
<li class="fragment"><p>The 5% is <span class="math inline">\(P(\text{match} \mid \text{innocent})\)</span></p></li>
<li class="fragment"><p>The jury needs <span class="math inline">\(P(\text{innocent} \mid \text{match})\)</span></p></li>
<li class="fragment"><p>In a city of 1,000,000, roughly 50,000 people match</p></li>
</ul>
</div>
<div class="fragment">
<p>The evidence is real, but it is nothing like 95%. People have gone to prison over this exact confusion. [we should make law students take stats…]</p>
</div>
</section>
<section id="algorithmic-bias" class="slide level2 smaller">
<h2>Algorithmic Bias?</h2>
<p><strong>COMPAS</strong> is a proprietary risk score used in bail and sentencing decisions across the United States. In 2016, ProPublica obtained scores for thousands of defendants in Broward County, Florida, and reported that the algorithm was racially biased.</p>
<ul>
<li class="fragment"><p><strong>ProPublica:</strong> among defendants who did <strong>not</strong> go on to reoffend, Black defendants had been flagged high risk at nearly <strong>twice</strong> the rate of white defendants</p></li>
<li class="fragment"><p><strong>Northpointe (the vendor):</strong> among defendants flagged high risk, the reoffense rate was about <strong>the same</strong> regardless of race - the score means the same thing for everyone</p></li>
</ul>
<div class="fragment">
<p>Both claims are correct. ProPublica published the data, so we can verify both ourselves - and then prove that they had to disagree.</p>
</div>
</section>
<section id="the-actual-data" class="slide level2 smaller">
<h2>The Actual Data</h2>
<p>Broward County, 2013–14: everyone scored by COMPAS at pretrial, followed for two years. We keep the two groups the dispute was about.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a>compas <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/compas-scores-two-years.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a></a>  <span class="fu">filter</span>(race <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"African-American"</span>, <span class="st">"Caucasian"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb9-3"><a></a>  <span class="fu">mutate</span>(<span class="at">high_risk =</span> score_text <span class="sc">!=</span> <span class="st">"Low"</span>)   <span class="co"># COMPAS decile score of 5+</span></span>
<span id="cb9-4"><a></a></span>
<span id="cb9-5"><a></a>compas <span class="sc">|&gt;</span></span>
<span id="cb9-6"><a></a>  <span class="fu">count</span>(race, high_risk, <span class="at">rearrested =</span> <span class="fu">ifelse</span>(two_year_recid <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"yes"</span>, <span class="st">"no"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb9-7"><a></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> rearrested, <span class="at">values_from =</span> n, <span class="at">names_prefix =</span> <span class="st">"rearrested_"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  race             high_risk rearrested_no rearrested_yes
  &lt;chr&gt;            &lt;lgl&gt;             &lt;int&gt;          &lt;int&gt;
1 African-American FALSE               990            532
2 African-American TRUE                805           1369
3 Caucasian        FALSE              1139            461
4 Caucasian        TRUE                349            505</code></pre>
</div>
</div>
<div style="font-size: 0.62em; color: grey;">
<p>propublica/compas-analysis on GitHub, <code>compas-scores-two-years.csv</code> — the file behind the article.</p>
</div>
</section>
<section id="both-sides" class="slide level2 smaller">
<h2>Both Sides</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>rates <span class="ot">&lt;-</span> compas <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a></a>  <span class="fu">group_by</span>(race) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a></a>  <span class="fu">summarise</span>(<span class="at">base_rate =</span> <span class="fu">mean</span>(two_year_recid),</span>
<span id="cb11-4"><a></a>            <span class="at">fpr =</span> <span class="fu">mean</span>(high_risk[two_year_recid <span class="sc">==</span> <span class="dv">0</span>]),   <span class="co"># P(flagged | not rearrested)</span></span>
<span id="cb11-5"><a></a>            <span class="at">fnr =</span> <span class="fu">mean</span>(<span class="sc">!</span>high_risk[two_year_recid <span class="sc">==</span> <span class="dv">1</span>]),  <span class="co"># P(not flagged | rearrested)</span></span>
<span id="cb11-6"><a></a>            <span class="at">ppv =</span> <span class="fu">mean</span>(two_year_recid[high_risk]))        <span class="co"># P(rearrested | flagged)</span></span>
<span id="cb11-7"><a></a>rates</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  race             base_rate   fpr   fnr   ppv
  &lt;chr&gt;                &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 African-American     0.514 0.448 0.280 0.630
2 Caucasian            0.394 0.235 0.477 0.591</code></pre>
</div>
</div>
<ul>
<li class="fragment"><p><strong>ProPublica’s number is <code>fpr</code>,</strong> <span class="math inline">\(P(\text{flagged} \mid \text{not rearrested})\)</span>: <strong>44.9%</strong> vs <strong>23.5%</strong>. Its mirror is <code>fnr</code>: rearrested white defendants were labeled low risk almost twice as often, <strong>47.7%</strong> vs <strong>28.0%</strong></p></li>
<li class="fragment"><p><strong>Northpointe’s number is <code>ppv</code>,</strong> <span class="math inline">\(P(\text{rearrested} \mid \text{flagged})\)</span>: <strong>63.0%</strong> vs <strong>59.1%</strong>. Roughly equal - a flag is calibrated.</p></li>
</ul>
<div class="fragment">
<p>Both computed correctly, from the same table. Crucially: the <strong>base rates differ</strong>, 51.4% vs 39.4%. That difference is the key to understanding this.</p>
</div>
</section>
<section id="you-have-already-derived-this" class="slide level2 smaller">
<h2>You Have Already Derived This</h2>
<p>Northpointe’s number is a posterior. Write Bayes’ rule for it, with the base rate <span class="math inline">\(p = P(\text{rearrested})\)</span> as the prior:</p>
<p><span class="math display">\[\text{PPV} = P(\text{rearrested} \mid \text{flagged}) = \frac{(1-\text{FNR})\,p}{(1-\text{FNR})\,p + \text{FPR}\,(1-p)}\]</span></p>
<ul>
<li class="fragment"><p>The numerator is the true positives; the denominator is everyone flagged — the law of total probability again</p></li>
<li class="fragment"><p>This is the cancer-screening formula relabeled: sensitivity <span class="math inline">\(= 1-\text{FNR}\)</span>, prior <span class="math inline">\(= p\)</span>.</p></li>
</ul>
</section>
<section id="solve-for-the-false-positive-rate" class="slide level2 smaller">
<h2>Solve for the False Positive Rate</h2>
<p>The identity runs both ways. Cross-multiply and isolate FPR:</p>
<p><span class="math display">\[\begin{aligned}
\text{PPV}\left[(1-\text{FNR})\,p + \text{FPR}\,(1-p)\right] &amp;= (1-\text{FNR})\,p \\[2pt]
\text{PPV} \cdot \text{FPR} \cdot (1-p) &amp;= (1-\text{FNR})\,p\,(1-\text{PPV}) \\[2pt]
\text{FPR} &amp;= \frac{p}{1-p} \cdot \frac{1-\text{PPV}}{\text{PPV}} \cdot (1-\text{FNR})
\end{aligned}\]</span></p>
<p>Given a group’s base rate, calibration, and miss rate, the false positive rate is not a free design choice. It is <strong>already determined</strong>.</p>
<div class="fragment">
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a>rates <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">fpr_check =</span> base_rate <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">-</span> base_rate) <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> ppv) <span class="sc">/</span> ppv <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> fnr))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  race             base_rate   fpr   fnr   ppv fpr_check
  &lt;chr&gt;                &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
1 African-American     0.514 0.448 0.280 0.630     0.448
2 Caucasian            0.394 0.235 0.477 0.591     0.235</code></pre>
</div>
</div>
<p>Exact in both groups, as it must be - this is accounting, not an assumption. The trap comes from reading it <strong>across</strong> groups.</p>
</div>
</section>
<section id="you-cannot-have-both" class="slide level2 smaller">
<h2>You Cannot Have Both</h2>
<p>Demand a “fair” algorithm: equal calibration (<span class="math inline">\(\text{PPV}_B = \text{PPV}_W\)</span>) and equal miss rates (<span class="math inline">\(\text{FNR}_B = \text{FNR}_W\)</span>). Divide one group’s identity by the other’s — everything cancels except the base rates:</p>
<p><span class="math display">\[\frac{\text{FPR}_B}{\text{FPR}_W} = \frac{p_B/(1-p_B)}{p_W/(1-p_W)} = \frac{0.514/0.486}{0.394/0.606} \approx 1.63\]</span></p>
<ul>
<li class="fragment"><p>Even a <em>perfectly</em> calibrated score with equal miss rates would flag harmless Black defendants at <strong>1.63 times</strong> the white rate. The observed gap is 1.9 times.</p></li>
<li class="fragment"><p>The only escapes are equal base rates or a perfect predictor. That is the point in <strong>Chouldechova (2017)</strong> and we just did the algebra.</p></li>
<li class="fragment"><p>Not an artifact of the High/Low cutoff: Kleinberg, Mullainathan, and Raghavan (2016) prove the same bind for continuous scores. (Statement only — that proof is beyond the scope of this course.)</p></li>
</ul>
<div class="fragment">
<p>No cleverer algorithm gets around this. It is arithmetic.</p>
</div>
</section>
<section id="what-does-reoffend-mean-here" class="slide level2 smaller">
<h2>What Does “Reoffend” Mean Here?</h2>
<p>Every claim so far said <em>reoffended</em>. Look at what the variable actually is: <code>two_year_recid</code> - <strong>a new arrest</strong> within two years.</p>
<ul>
<li class="fragment"><p>Arrest is not behavior. If one group is policed more heavily, its <strong>measured</strong> base rate rises even if underlying behavior were identical.</p></li>
<li class="fragment"><p>The base rate drives everything on the last three slides - the forced FPR gap is a gap in <span class="math inline">\(p\)</span> <em>as measured through policing</em></p></li>
<li class="fragment"><p>This is (in part) a measurement validity question. If the base rate difference is accurately reflecting behavior, Northpointe’s algorithm is not biased. If the groups are treated differently, it is biased.</p></li>
</ul>
<div class="fragment">
<p>The impossibility result is about the world <strong>as measured</strong>. As social scientists, we need to think through both the equations <em>and</em> the data generating process.</p>
</div>
</section>
<section id="which-conditional-probability-matters" class="slide level2 smaller">
<h2>Which Conditional Probability Matters?</h2>
<ul>
<li class="fragment"><p>Both sides computed correctly from the same eight cells.</p></li>
<li class="fragment"><p><span class="math inline">\(P(\text{flagged} \mid \text{not rearrested})\)</span> what happens to people who are flagged?</p></li>
<li class="fragment"><p><span class="math inline">\(P(\text{rearrested} \mid \text{flagged})\)</span> what is a flag worth as evidence?</p></li>
<li class="fragment"><p>When base rates differ, no algorithm answers both symmetrically. Choosing is a <strong>normative</strong> decision, not a mathematical one!</p></li>
</ul>
<div class="fragment">
<p>Bail, lending, hiring, medical triage: every algorithmic fairness fight is an argument about <strong>which conditional probability matters</strong>.</p>
</div>
</section>
<section id="paul-the-octopus-revisited" class="slide level2">
<h2>Paul the Octopus, Revisited</h2>
<p>We left this hanging last time. Paul went 8-for-8, which is <span class="math inline">\(1/256\)</span> by chance.</p>
<ul>
<li class="fragment"><p>Let <span class="math inline">\(A\)</span> = “Paul is genuinely prophetic”</p></li>
<li class="fragment"><p><span class="math inline">\(P(8\text{-for-}8 \mid A) = 1\)</span></p></li>
<li class="fragment"><p><span class="math inline">\(P(8\text{-for-}8 \mid A^{c}) = 1/256\)</span></p></li>
<li class="fragment"><p>And the prior, <span class="math inline">\(P(A)\)</span> = the base rate of psychic cephalopods</p></li>
</ul>
</section>
<section id="priors-matter" class="slide level2 smaller">
<h2>Priors Matter</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a>paul <span class="ot">&lt;-</span> <span class="cf">function</span>(prior) prior <span class="sc">/</span> (prior <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">-</span> prior) <span class="sc">*</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">256</span>))</span>
<span id="cb15-2"><a></a></span>
<span id="cb15-3"><a></a><span class="fu">paul</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">100</span>)      <span class="co"># generous: 1 in 100 octopuses is psychic</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7211268</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a></a><span class="fu">paul</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">1000</span>)     <span class="co"># 1 in 1,000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2039841</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="fu">paul</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">1000000</span>)  <span class="co"># 1 in a million</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0002559347</code></pre>
</div>
</div>
<div class="fragment">
<ul>
<li class="fragment"><p>The evidence is identical in all three. The conclusion is differs based on our priors.</p></li>
<li class="fragment"><p>Eight correct picks is a <strong>huge</strong> update — a 1-in-1,000 prior becomes 1-in-5</p></li>
<li class="fragment"><p>But start from a sane prior about octopuses and Paul is still almost certainly just lucky</p></li>
</ul>
</div>
</section>
<section id="what-bayes-is-really-doing" class="slide level2">
<h2>What Bayes Is Really Doing</h2>
<ul>
<li class="fragment"><p>It is a rule for <strong>updating belief in light of evidence</strong></p></li>
<li class="fragment"><p>Strong evidence cannot rescue an implausible hypothesis on its own</p></li>
<li class="fragment"><p>Bayes formalizes something we’ve already seen: <em>how many chances did the world have?</em></p></li>
</ul>
<div class="fragment">
<p>This is also an entire branch of statistics. If it appeals to you, take a Bayesian course! (I don’t really consider myself a Bayesian, but they definitely have some good points)</p>
</div>
</section>
<section id="section" class="slide level2">
<h2></h2>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>