---
title: "POSC 8410 (Fall 2026)"
---

Course slides for **POSC 8410**, Clemson University, Fall 2026.
Mon & Wed, 2:30–3:45 PM, 212 Brackett Hall.


## Slides

| Date | Topic | Slides |
|------|-------|--------|
| Aug 19 | Introduction | [HTML](01_Introduction.html){target="_blank"} |
| Aug 24 | R Foundations | [HTML](02_R_Foundations.html){target="_blank"} |
| Aug 26 | Data Wrangling | [HTML](03_Wrangling_Visualization.html){target="_blank"} |
| Aug 31 | Describing Data | [HTML](04_Describing_Data.html){target="_blank"} |
| Sep 2  | Probability Foundations | [HTML](05_Probability_Foundations.html){target="_blank"} |
| Sep 9  | Conditional Probability and Bayes | [HTML](06_Conditional_Probability_Bayes.html){target="_blank"} |
| Sep 14 | Independence and Dangers of Conditioning | [HTML](07_Independence_Simpsons_Colliders.html){target="_blank"} |
| Sep 16 | Random Variables and Discrete Distributions | [HTML](08_Random_Variables_Binomial.html){target="_blank"} |
| Sep 21 | Expectation and Variance | [HTML](09_Expectation_Variance.html){target="_blank"} |

Slides are posted here before each class.
